# ============================================================
#  Nexo Box - Windows 10 host installer (native QEMU + WHPX engine)
#  Called by install.ps1 when the host is Windows 10 (build < 22000),
#  where dockur/windows cannot run (no /dev/kvm on Win10 WSL2).
#
#  Steps: enable Windows Hypervisor Platform (reboot, auto-resume) ->
#  install QEMU -> generate .env -> build the base disk with a hands-off
#  Windows install (autounattend on a config CD) -> wait for the guest's
#  MCP server to answer -> leave the base running.
#  Idempotent; compatible with Windows PowerShell 5.1. ASCII-only.
# ============================================================
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
. (Join-Path $PSScriptRoot 'qemu.ps1')

function Write-Step($msg) { Write-Host ''; Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    OK: $msg" -ForegroundColor Green }
function Write-Warn($msg)  { Write-Host "    WARNING: $msg" -ForegroundColor Yellow }

function Get-InteractiveUser {
    try {
        $p = Get-CimInstance Win32_Process -Filter "name='explorer.exe'" | Select-Object -First 1
        if ($p) { $o = Invoke-CimMethod -InputObject $p -MethodName GetOwner; if ($o.User) { return ($o.Domain + '\' + $o.User) } }
    } catch { }
    return ($env:USERDOMAIN + '\' + $env:USERNAME)
}

$interactiveUser = Get-InteractiveUser
try { Unregister-ScheduledTask -TaskName 'NexoBoxInstall' -Confirm:$false -ErrorAction Stop } catch { }

Write-Host '============================================'
Write-Host ' Nexo Box - Windows 10 engine (QEMU + WHPX)'
Write-Host '============================================'

# ---------- 1. Pre-checks ----------
Write-Step 'Checking prerequisites'
$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$cs  = Get-CimInstance Win32_ComputerSystem
if (-not $cs.HypervisorPresent -and -not $cpu.VirtualizationFirmwareEnabled) {
    throw "Virtualization is disabled in firmware. Enable 'AMD SVM' (or 'Intel VT-x') in the BIOS/UEFI and run install.bat again."
}
Write-Ok "Windows 10 + virtualization available (user: $interactiveUser)"

# ---------- 2. Windows Hypervisor Platform (WHPX backend for QEMU) ----------
Write-Step 'Ensuring Windows Hypervisor Platform (WHPX)'
$whp = Get-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -ErrorAction SilentlyContinue
if (-not $whp -or $whp.State -ne 'Enabled') {
    Write-Host '    Enabling HypervisorPlatform (a reboot is required)...'
    Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -All -NoRestart | Out-Null

    # schedule an elevated resume at logon (survives a denied UAC prompt)
    $batPath = Join-Path $root 'install.bat'
    try {
        $action    = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument ('/c start "" "' + $batPath + '"')
        $trigger   = New-ScheduledTaskTrigger -AtLogOn -User $interactiveUser
        $principal = New-ScheduledTaskPrincipal -UserId $interactiveUser -LogonType Interactive -RunLevel Highest
        Register-ScheduledTask -TaskName 'NexoBoxInstall' -Action $action -Trigger $trigger -Principal $principal -Force | Out-Null
        Write-Host '    After the reboot the installer REOPENS ON ITS OWN and continues.'
    } catch {
        Write-Warn "Could not schedule the automatic resume ($_). After restarting, run install.bat again."
    }
    $answer = Read-Host '    Restart NOW? (Y/N)'
    if ($answer -match '^[yY]') { shutdown /r /t 5; exit 0 }
    Write-Host '    Ok - restart manually when you can; the installation continues after the reboot.'
    exit 0
}
Write-Ok 'Windows Hypervisor Platform enabled'

# ---------- 3. QEMU ----------
Write-Step 'Ensuring QEMU (native Windows build)'
$qemuExe = Install-Qemu
Write-Ok "QEMU ready: $qemuExe"

# ---------- 4. Config (.env + MCP key) ----------
Write-Step 'Configuring the box'
$envFile = Join-Path $root '.env'
if (-not (Test-Path $envFile)) {
    $key = [guid]::NewGuid().ToString('N') + [guid]::NewGuid().ToString('N')
    @(
        '# Nexo Box configuration. Generated by the installer.',
        '# Windows 10 host: the native QEMU + WHPX engine is used and a local',
        '# Windows .iso in this folder is REQUIRED (QEMU cannot download Windows).',
        'BOX_RAM_SIZE=4G',
        'BOX_CPU_CORES=2',
        'BOX_DISK_SIZE=32G',
        'BOX_USERNAME=Docker',
        'BOX_PASSWORD=admin',
        "MCP_AUTH_KEY=$key",
        '# Optional: a numeric Steam app id to auto-install in the box.',
        'STEAM_APP_ID='
    ) | Set-Content -Path $envFile -Encoding ascii
    Write-Ok '.env created with a new MCP key'
} else {
    Write-Ok '.env already exists (kept)'
}
function Get-EnvValue([string]$name, [string]$default = '') {
    $line = Get-Content $envFile | Where-Object { $_ -match "^$name=" } | Select-Object -First 1
    if ($line) { return ($line -replace "^$name=", '').Trim() }
    return $default
}
$key   = Get-EnvValue 'MCP_AUTH_KEY'
$ram   = Get-EnvValue 'BOX_RAM_SIZE' '4G'
$cores = [int](Get-EnvValue 'BOX_CPU_CORES' '2')
$dsize = Get-EnvValue 'BOX_DISK_SIZE' '32G'
$appId = Get-EnvValue 'STEAM_APP_ID'
if (-not $key) { throw 'MCP_AUTH_KEY not found in .env - delete the .env and run again.' }

$storage = Join-Path $root 'storage'
New-Item -ItemType Directory -Force -Path $storage | Out-Null

# ---------- 5. Windows ISO (required on this engine) ----------
Write-Step 'Looking for a Windows ISO in the folder'
$iso = Get-ChildItem -Path $root -Filter *.iso -File -ErrorAction SilentlyContinue |
       Sort-Object Length -Descending | Select-Object -First 1
if (-not $iso) {
    throw 'No .iso found. Put a Windows 10 x64 .iso next to install.bat (the QEMU engine installs Windows from it) and run install.bat again.'
}
Write-Ok "Using ISO: $($iso.Name)"

# ---------- 6. Base disk ----------
$baseDisk = Join-Path $storage 'base.qcow2'
if (Test-Path $baseDisk) {
    Write-Warn "Base disk already exists ($baseDisk). Delete it to reinstall the base from scratch."
} else {
    Write-Step 'Creating the base disk (thin qcow2)'
    $qemuImg = Find-QemuImg
    if (-not $qemuImg) { throw 'qemu-img.exe not found next to QEMU.' }
    & $qemuImg create -f qcow2 $baseDisk $dsize | Out-Null
    if (-not (Test-Path $baseDisk)) { throw 'qemu-img could not create the base disk.' }
    Write-Ok "Base disk created ($dsize cap, thin)"
}

# ---------- 7. Config CD (autounattend + provisioning + live key) ----------
Write-Step 'Building the config CD (unattended answer file + provisioning)'
$baseCfgIso = Join-Path $storage 'base-config.iso'
Build-NexoConfigIso -OutIso $baseCfgIso -Key $key -AppId $appId -IncludeInstaller | Out-Null
Write-Ok "Config CD built: $baseCfgIso"

# ---------- 8. Unattended install ----------
# If Windows is already installed (MCP answers on 8000) we skip straight to done.
$ports = Get-VmPorts -Slot 0
if (Wait-Mcp -Port $ports.McpPort -TimeoutSec 3) {
    Write-Ok 'Base already provisioned (MCP is answering) - nothing to install.'
} else {
    Write-Step 'Installing Windows into the base (hands-off; 20-40 min)'
    $vmArgs = Get-VmArgs -Name 'nexo-base' -DiskPath $baseDisk -Ram $ram -Cores $cores -Slot 0 `
                         -InstallIso $iso.FullName -ConfigIso $baseCfgIso
    # Run under a relaunch loop: QEMU exits when Setup reboots (WinPE->installed);
    # the loop relaunches it (booting the disk) so the install runs to completion.
    $loopBat = Join-Path $storage 'base-install-loop.bat'
    $errLog  = Join-Path $storage 'base-install.err'
    Start-InstallLoop -VmArgs $vmArgs -LoopBat $loopBat -ErrLog $errLog
    Write-Ok "Installer started. Watch the screen with a VNC viewer at 127.0.0.1:$($ports.VncPort)."

    # tap Enter past the CD's "Press any key to boot from CD" prompt (first boot only;
    # later relaunches get no taps, so the CD times out and the installed disk boots)
    Write-Host '    Getting past the boot prompt...'
    Push-BootPrompt -MonPort $ports.MonPort -Seconds 18

    Write-Host '    Waiting for Windows to install and provision (MCP)... (hands-off)'
    $ok = Wait-Mcp -Port $ports.McpPort -TimeoutSec 3000

    # stop the install loop; the base is a template (instances are clones of it)
    Stop-InstallLoop -LoopBat $loopBat
    $pr = Get-VmProcess -Name 'nexo-base'
    if ($pr) { Stop-Vm -MonPort $ports.MonPort -ProcessId ([int]$pr.ProcessId) | Out-Null }

    if ($ok) {
        Write-Ok 'Base built: Windows installed, provisioned, and MCP answered. Base is now a stopped template.'
    } else {
        Write-Warn "MCP did not answer within the time limit. The install may still need time - watch VNC 127.0.0.1:$($ports.VncPort), or re-run install.bat to resume."
    }
}

# ---------- 9. Summary ----------
Write-Step 'Windows 10 host setup complete!'
Write-Host ''
Write-Host '  Engine: native QEMU + WHPX (no Docker/WSL needed on Windows 10).'
Write-Host '  Base box: storage\base.qcow2 (clone it from NexoGate to make instances).'
Write-Host ''
Write-Host '  Access to the BASE (this PC only):'
Write-Host "   - Screen (VNC):  127.0.0.1:$($ports.VncPort)   (use any VNC viewer)"
Write-Host "   - RDP:           127.0.0.1:$($ports.RdpPort)   (user Docker / password admin)"
Write-Host "   - AI (MCP HTTP): http://127.0.0.1:$($ports.McpPort)/mcp   key: $key"
Write-Host ''
Write-Host '  Open NexoGate to create/clone/monitor instances:  nexo.bat'
Write-Host ''
